### ISSUE TITLE
Issueってこんな感じの機能

### ISSUE THREAD

**Issue by ayaha401** [komugikoShimizu/Zenject_Test#2]
# Issueですること
プログラムの議論をしたり、修正案を出したりするよ

# 例えば
https://github.com/komugikoShimizu/Zenject_Test/blob/28846c5d077fe3828b20efa5c0f544c752ef68d9/ZenjectTest/Assets/Scripts/InputScripts_Mono.cs#L12-L15
いい感じのメソッド名だね

こんな感じにプログラムの一部分を表示して議論したりできる。
青色の場所をクリックするとプログラムに飛べる。

# これで何するの？
今までのように口頭でプログラムの修正箇所を使えたり議論をしていると忘れてしまったりするのでこのIssueを使って修正箇所をリストアップできるようにして使うよ

**全部読めたらこのIssueの下に返信をしてみて**

**Comment by komugikoShimizu** [comment]
なんとなく理解できた
確かにこの機能便利やね

**Comment by ayaha401** [comment]
Openってなってたら今議論中って感じ、議論だったり修正が終わったらIssueを右下の`Close with comment`を押すことでCloseできる。Closeってのは議論が終わったってことね。
終わったので閉じます
